name = "sg1"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "df.game.naver.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "zoomcares.zoom.us.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "stage-7.duolingo.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "sb.scorecardresearch.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "go.appannie.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "lipcon.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "img.email1.vidio.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "img.email2.vidio.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "img.email3.vidio.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "api.webex.com.sg1.idstore.biz.id"
custom_domain = true

[[routes]]
pattern = "investor.fb.com.sg1.idstore.biz.id"
custom_domain = true


[vars]
PROXYIP = "134.209.97.92"
UUID = "1d30fa45-9d31-4e81-a646-f8c7dbda0c65"
