name = "sg3"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "df.game.naver.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "zoomcares.zoom.us.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "stage-7.duolingo.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "sb.scorecardresearch.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "go.appannie.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "lipcon.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "img.email1.vidio.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "img.email2.vidio.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "img.email3.vidio.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "api.webex.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "investor.fb.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "www.wasa.com.sg3.vipstore.cloud"
custom_domain = true

[[routes]]
pattern = "z-p15.www.instagram.com.sg3.vipstore.cloud"
custom_domain = true


[vars]
PROXYIP = "52.74.101.26"
UUID = "1d30fa45-9d31-4e81-a646-f8c7dbda0c65"
