name = "id2"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "dl.cvs.freefiremobile.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "df.game.naver.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "zaintest.vuclip.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "api.midtrans.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "edu.ruangguru.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "beta.zoom.us.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "api.zoom.us.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "store.zoom.us.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "zoomgov.socifiles.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "access.zoominfo.com.id2.wcprem.my.id"
custom_domain = true

[[routes]]
pattern = "data.mt.id2.wcprem.my.id"
custom_domain = true

[vars]
PROXYIP = "203.194.112.119"
UUID = "1d30fa45-9d31-4e81-a646-f8c7dbda0c65"
